h5ad_file: "/localscratch/schockalingam6/tmp/rsc.5k/adata_lei.100k.5k.h5ad"
tf_csv_file: "data/pbmc/trrust_tf.txt"
nroundup: 3
output_file: /localscratch/schockalingam6/tmp/rsc.5k/rsc.5k.h5
#mode: gb_grn
mode: cv_gb
gbm_params:
  verbose: 0
  num_threads: 2
n_sample_genes: 500
