h5ad_file: "./data/pbmc_scrna/0100K/rsc_lei.100K.5K.h5ad"
misi_data_file: "./out/adata.100K.5K.misidata.h5"
puc_file: "./out/adata.100K.5K.lmr_puc.h5"
pidc_file: "./out/adata.100k.5K.lmr_pidc.h5"
#
nrounds: 0
nsamples: 0
nobs: 0
nvars: 0
mode:
  - "puc_lmr"
  #- "samples_ranges"
  #- "puc2pidc"
tbase: "2"
save_nodes: False
save_node_pairs: True
