h5ad_file: "./data/pbmc_scrna/0020K/adata.20K.0K500.h5ad"
misi_data_file: "./out/adata.20k.500.misidata.h5"
puc_file: "./out/adata.20k.500.lmr_puc.h5"
pidc_file: "./out/adata.20k.500.lmr_pidc.h5"
#
nrounds: 0
nsamples: 0
nobs: 0
nvars: 0
mode:
  - misi
  #- "samples_ranges"
  #- "puc2pidc"
tbase: "e"
save_nodes: False
save_node_pairs: True
