h5ad_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.h5ad"
misi_data_file: "tmp/adata.20k.500.misidata.h5"
puc_file: "tmp/adata.20k.500.lmr_puc.h5"
pidc_file: "tmp/adata.20k.500.lmr_pidc.h5"
#
nrounds: 0
nsamples: 20
nobs: 0
nvars: 0
mode:
  - "misi"
  #- "samples_ranges"
  #- "puc2pidc"
tbase: "e"
save_nodes: False
save_node_pairs: True
